### ISSUE TITLE
Error on loading c4ddev-loader.pyp

### ISSUE THREAD

**Issue by MikeUdin** [NiklasRosenstein/c4ddev#16]
There is a error in the Console Cinema4d after starting program

> Traceback (most recent call last):
>   File "'c4ddev-loader.pyp'", line 360, in <module>
>   File "<string>", line 382, in exec_
>   File "C:\Users\Dude\AppData\Roaming\MAXON\CINEMA 4D R17_8DE13DAD\plugins\c4ddev-0.1.3\lib\c4ddev\main.py", line 35, in <module>
>     require('./resource')
>   File "<string>", line 452, in __call__
>   File "<string>", line 819, in resolve_and_load
>   File "<string>", line 800, in load_module
>   File "<string>", line 382, in exec_
>   File "C:\Users\Dude\AppData\Roaming\MAXON\CINEMA 4D R17_8DE13DAD\plugins\c4ddev-0.1.3\lib\c4ddev\resource.py", line 35, in <module>
>     from nr.parse import strex
> ImportError: No module named nr.parse

**Comment by NiklasRosenstein** [comment]
Thanks for reporting this issue. Seems like I forgot to include the package. I'll upload an updated release in a bit.

**Comment by NiklasRosenstein** [comment]
Just published a Windows release of 0.1.6: https://github.com/NiklasRosenstein/c4ddev/releases

It was compiled with R18, so the Python C extensions won't work in older Cinema 4D versions. The Python plugins work in older versions.
